Upgrade alpine + reformat/lint

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,38 +1,53 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-set -ue
+set -ueo pipefail
 
-PATH=/usr/local/bin:$PATH
+# Ensure ARM64 homebrew and /usr/local/bin are in PATH first.
+# This finds /usr/local/bin/lintball and finds newer Homebrew-installed bash.
+export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
 
 echo "Checking for .github/workflows/build.yml.jinja changes..."
 
-if [ "$(git diff-index --cached HEAD --name-only)" != "" ]
-then
+if [ "$(git diff-index --cached HEAD --name-only)" != "" ]; then
 
-	files=( $(git diff-index --cached HEAD --name-only) )
+  mapfile -t files < <(git diff-index --cached HEAD --name-only)
 
-	for file in ${files[@]}
-	do
-		if [ "$file" == ".github/workflows/build.yml.jinja" ]
-		then
-			echo "Change detected, re-rendering GitHub Actions"
-			pipenv run ./builder.py render-github-actions
-			git add .github/workflows/*.yml || true
-		elif [ "$file" == "README.md.jinja" ]
-		then
-				echo "Change detected, re-rendering README"
-			pipenv run ./builder.py render-readme
-			git add README.md || true
-		fi
+  for file in "${files[@]}"; do
+    if [ "$file" == ".github/workflows/build.yml.jinja" ]; then
+      echo "Change detected, re-rendering GitHub Actions"
+      pipenv run ./builder.py render-github-actions
+      git add .github/workflows/*.yml || true
+    elif [ "$file" == "README.md.jinja" ]; then
+      echo "Change detected, re-rendering README"
+      pipenv run ./builder.py render-readme
+      git add README.md || true
+    fi
+  done
+fi
 
-		case $file in
-			*.py)
-				if [ -f "$file" ]
-				then
-					pipenv run black $file
-					git add $file
-				fi
-				;;
-		esac
-	done
+if [ -f "${LINTBALL_DIR:-.}/bin/lintball" ]; then
+  "${LINTBALL_DIR:-.}/bin/lintball" pre-commit
+elif [ -n "$(command -v lintball)" ]; then
+  lintball pre-commit
+else
+  {
+    echo
+    echo "Error: could not find a lintball executable, but lintball's pre-commit hook is enabled."
+    echo
+    echo "Solutions:"
+    echo
+    echo '- Install lintball globally:'
+    echo '    npm install -g lintball'
+    echo '- And/or, ensure that that lintball can be found in PATH:'
+    # shellcheck disable=SC2016
+    echo '    ln -s "$(command -v lintball)" /usr/local/bin/'
+    echo
+    echo 'Workarounds:'
+    echo
+    echo '- Disable all git hooks:'
+    echo '    git config --local core.hooksPath ""'
+    echo "- Delete ${BASH_SOURCE[0]}"
+    echo
+  } >&2
+  exit 1
 fi
